on: [push]

name: build

jobs:
  check:
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test